namespace :xml do
  desc "Scrapps whole xml"
  task :all do
    puts "Articles..."
    require './article_job'
    puts "Journals..."
    require './journal_job'
    puts "Volumes..."
    require './volume_job'
    puts "Years..."
    require './years_job'
    puts "Numbers..."
    require './numbers_job'
    puts "Done..."
  end
end
